apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: acinamespaces.rmlab.cisco.com
spec:
  group: rmlab.cisco.com
  names:
    kind: AciNamespace
    listKind: AciNamespaceList
    plural: acinamespaces
    shortNames:
    - aci
    singular: acinamespace
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The EPG Contract Master used as a template
      jsonPath: .spec.epgcontractmaster
      name: EPG-CONTRACT-MASTER
      priority: 0
      type: string
    - description: ACI Bridge Domain
      jsonPath: .status.bridge_domain
      name: ACI-BD
      priority: 0
      type: string
    - description: Consumer contracts of the Master EPG
      jsonPath: .status.mepg_consumer_contracts
      name: M-EPG-C-CONTRACTS
      priority: 1
      type: string
    - description: Provider contracts of the Master EPG
      jsonPath: .status.mepg_provider_contracts
      name: M-EPG-P-CONTRACTS
      priority: 1
      type: string
    - description: Consumer contracts of EPG
      jsonPath: .status.consumer_contracts
      name: C-CONTRACTS
      priority: 1
      type: string
    - description: Provider contracts of EPG
      jsonPath: .status.provider_contracts
      name: P-CONTRACTS
      priority: 1
      type: string
    - description: True if the operator manages the implementation. If False, if you delete the AciNamespace the controller will not execute any finaliser
      jsonPath: .spec.op_managed
      name: MANAGED
      priority: 0
      type: boolean
    name: v1
    schema:
      openAPIV3Schema:
        description: ACI CNI Namespace
        properties:
          spec:
            properties:
              applicationprofile:
                default: kubernetes
                type: string
              bridgedomain:
                default: kube-pod-bd
                type: string
              epgcontractmaster:
                default: N/A
                type: string
              op_managed:
                type: boolean
              openshiftproject:
                default: false
                type: boolean
            required:
            - op_managed
            type: object
          status:
            properties:
              bridge_domain:
                type: string
              consumer_contracts:
                type: string
              mepg_consumer_contracts:
                type: string
              mepg_dn:
                type: string
              mepg_provider_contracts:
                type: string
              provider_contracts:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
