# This will only work on Kubernetes < 1.6
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: acinamespaces.rmlab.cisco.com
spec:
  group: rmlab.cisco.com
  scope: Cluster
  names:
    kind: AciNamespace
    listKind: AciNamespaceList
    plural: acinamespaces
    singular: acinamespace
    shortNames:
    - aci
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      description: "ACI CNI Namespace"
      properties:
        spec:
          required: ["epgcontractmaster", "openshift_project"]
          type: object
          properties:
            epgcontractmaster:
              type: string
            openshift_project:
              type: boolean
