apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: acinamespaces.rmlab.cisco.com
spec:
  group: rmlab.cisco.com
  scope: Cluster
  names:
    kind: AciNamespace
    listKind: AciNamespaceList
    plural: acinamespaces
    singular: acinamespace
    shortNames:
    - aci
  subresources:
    status: {}
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      description: "ACI CNI Namespace"
      properties:
        spec:
          required: ["epgcontractmaster", "openshiftproject", "acicleanup"]
          type: object
          properties:
            epgcontractmaster:
              type: string
            openshiftproject:
              type: boolean
            acicleanup:
              type: boolean
  additionalPrinterColumns:
    - name: EPG_CONTRACT_MASTER
      type: string
      description: The EPG Contract Master used as a template
      JSONPath: .spec.epgcontractmaster
    - name: IS_OPENSHIFT
      type: boolean
      description: Is this an openshift project?
      JSONPath: .spec.openshiftproject
    - name: ACI_CLEANUP
      type: boolean
      description: Remove ACI object when CR is deleted
      JSONPath: .spec.acicleanup